config/routes.rb
Rails.application.routes.draw do
  devise_for :users

    devise_scope :user do
      get "register",to: "devise/registrations#new", as: :register
      get "login", to: "devise/sessions#new", as: :login
      get "logout", to: "devise/sessions#destroy", as: :logout

    end

  resources :statuses
    get 'feed', to: "statutes#index", as: :feed
    root 'statuses#index'

    get '/:id', to: 'profiles#show' , as: 'profile'

end

app/models/document.rb
class Document < ActiveRecord::Base
  has_attached_file :attachments
end

app/models/status.rb
class Status < ActiveRecord::Base
  belongs_to :user
  belongs_to :document

  accepts_nested_attributes_for :document

  validates :content, presence: true,
                    length: { minimum: 2 }

  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :statuses
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :profile_name, presence: true, uniqueness: true


    def full_name
     full_name = "#{first_name}  #{last_name}"
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_params, if: :devise_controller?


  protected

    def configure_permitted_params
      devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:first_name, :last_name,
                                                :profile_name, :email, :password, :remember_me,
                                                 :password_confirmation)}
    end
end

app/controllers/profile_controller.rb
class ProfilesController < ApplicationController

  def show
    @user = User.find_by(params[:id])
    if @user
      @statuses = @user.statuses.all
      render  'show'
    else
      render file: 'public/404', status: 404, formats: [:html]
    end
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  # GET /statuses
  # GET /statuses.json
  def index
    @user = User.find_by(params[:id])
    @statuses = Status.all

  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
    @statuses = Status.all
  end

  # GET /statuses/new
  def new
    @status = Status.new
    @status.build_document
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:content, :user_id, document_attributes: [ :status_id, :user_id, :attachments ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">×</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
      <ul>
        <li>
          <a href ="#" data-dismiss="alert" class="close">x</a>
          <%= value %>
        </li>
      </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TreebookApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container-fluid">
  <div class="row">
    <div class="col-xs-2 nav-container">
      <a class="navbar-brand" href="#"> TreeBook </a>
      <ul class="nav nav-pills nav-stacked">
        <li class="active"><%= link_to "All Statuses", feed_path %></li>
      <% if user_signed_in? %>
        <li class="active"><%= link_to current_user.full_name , edit_user_registration_path %></li>
        <li class="active"><%= link_to "Log Out " ,  logout_path %></li>
      <% else %>
        <li class="active"><%= link_to "Sign Up" ,  register_path %></li>
        <li class="active"><%= link_to "Log In" , login_path %></li>
         <!--Sidebar content-->
      <% end %>
      </ul>
    </div>
    <div class="col-xs-10 page-content-container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </div>
</div>
</body>
</html>

app/views/statuses/_form.html.erb
<%= simple_form_for(@status, multipart: true, class: 'form-control') do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= f.input :user_id, collection: User.all, label_method: :full_name %>
    <%= f.input :content, as: :text, placeholder: "Write something interesting" %>
    <%= f.fields_for :document do |document_fields| %>
      <%= document_fields.input :attachment, as: :file %>
    <% end %>

    <div class:"form-action">
        <%= f.button :submit, class:"btn btn-primary"%>
    </div>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing Status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<div class="page-header">
  <h1> All of the Statuses </h1>
</div>

<%= link_to "Post a new status", new_status_path, class: "btn btn-success" %>

<% @statuses.each do |status| %>
  <div class="status">
      <strong>Name: <%= status.user.full_name %></strong>
      <p><%= status.content %></p>
      <div class="meta">
        <%= link_to time_ago_in_words(status.created_at) + " ago" , status %>
        <span class="admin">
          | <%= link_to "Edit", edit_status_path(status) %> |
          <%= link_to "Delete", status ,  method: :delete, data: {confirm: "Are you sure you want to delete this status"} %>
        </span>
      </div>
  </div>
<% end %>

app/views/statuses/new.html.erb
<h1>New Status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p>
  <strong>Name: <%= @status.user.full_name %></strong>

</p>

<p>
  <strong>Content:</strong>
  <%= @status.content %>
</p>
  <% if @status.document  %>
    <span class='label label-info'> Attachment </span>
      
  <% end %>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>